version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  backend:
    logging:
      driver: "none"
    restart: on-failure
    image: pejdzor/dronhub_backend:latest
    depends_on:
      - rabbitmq
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - shared_directory:/usr/shared_directory

  simulator:
    logging:
      driver: "none"
    restart: on-failure
    image: pejdzor/dronhub_simulator:latest
    environment:
      RABBITMQ_HOST: "rabbitmq"
    networks:
      - app-network
    volumes:
      - shared_directory:/usr/shared_directory

  frontend:
    logging:
      driver: "none"
    image: pejdzor/dronhub_frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  shared_directory:

networks:
  app-network:
    driver: bridge
