version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  backend:
    restart: on-failure
    logging:
      driver: "none"
    build:
      context: backend
      dockerfile: Dockerfile-dev
    depends_on:
      - rabbitmq
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/dronhub
      DATABASE_USERNAME: dronhub
      DATABASE_PASSWORD: passwd
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - shared_directory:/usr/shared_directory

  simulator:
    logging:
      driver: "none"
    restart: on-failure
    build:
      context: simulator
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: "rabbitmq"
    networks:
      - app-network
    volumes:
      - shared_directory:/usr/shared_directory
      - $PWD/config:/usr/config

  frontend:
    logging:
      driver: "none"
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  mysql_data:
  shared_directory:

networks:
  app-network:
    driver: bridge