FROM gradle:7.2.0-jdk17

COPY . /usr/dronhub

WORKDIR /usr/dronhub

RUN ./gradlew build -x test

CMD ["java", "-Dspring.profiles.active=develop" ,"-jar", "./build/libs/dronhub_backend-0.0.1-SNAPSHOT.jar", "> /dev/null"]
EXPOSE 8080