spring:
  application:
    name: backend
  datasource:
    url: "jdbc:h2:./default"
    #url: jdbc:postgresql://localhost:5432/dronhub
    #username: dronhub
    #password: zaq12wsx
    #driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
sharedfolder:
  path: "/shared_directory/"
