spring:
  config:
    activate:
      on-profile: develop
  application:
    name: dronhub_backend
  datasource:
    url: jdbc:h2:./default
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: dronhub_backend
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
---
sharedfolder:
  path: "/shared_directory/"
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest