spring:
  application:
    name: backend
  datasource:
    url: "jdbc:h2:./default"
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
sharedfolder:
  path: "/shared_directory/data.csv"
  interval: 2000
