name: Build Docker Images

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Run tests
        working-directory: ./backend
        run: ./gradlew test


  build-backend-develop:
    if: github.event.pull_request.merged == true
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build backend
        working-directory: ./backend
        run: ./gradlew clean build

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.dockerhub_username }}
          DOCKER_PASSWORD: ${{ secrets.dockerhub_password }}
        run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" docker.io

      - name: Build Docker image
        working-directory: ./backend
        run: docker build . --file Dockerfile-dev --tag pejdzor/dronhub_backend

      - name: Tag with commit
        run: docker image tag pejdzor/dronhub_backend pejdzor/dronhub_backend:${{github.sha}}

      - name: Push docker image
        run: docker push pejdzor/dronhub_backend:${{github.sha}}

  build-frontend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: v22.2.0

      - name: Run npm install
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.dockerhub_username }}
          DOCKER_PASSWORD: ${{ secrets.dockerhub_password }}
        run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" docker.io

      - name: Build Docker image
        working-directory: ./frontend
        run: docker build . --file Dockerfile --tag pejdzor/dronhub_frontend

      - name: Tag with commit
        run: docker image tag pejdzor/dronhub_frontend pejdzor/dronhub_frontend:${{github.sha}}

      - name: Push docker image
        run: docker push pejdzor/dronhub_frontend:${{github.sha}}
